# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:12:39+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    GovidCertificatePostRequest,
    GovidCertificatePostResponse,
    GovidCertificatePostResponse1,
    GovidCertificatePostResponse2,
    GovidCertificatePostResponse3,
    GovidCertificatePostResponse4,
    GovidCertificatePostResponse5,
    GovidCertificatePostResponse6,
    PhcerCertificatePostRequest,
    PhcerCertificatePostResponse,
    PhcerCertificatePostResponse1,
    PhcerCertificatePostResponse2,
    PhcerCertificatePostResponse3,
    PhcerCertificatePostResponse4,
    PhcerCertificatePostResponse5,
    PhcerCertificatePostResponse6,
)

app = MCPProxy(
    description='APIs provided by Maharashtra Council of Indian Medicine.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Maharashtra Council of Indian Medicine',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/mcimindia/v3'}],
)


@app.post(
    '/govid/certificate',
    description=""" API to verify ID Card. """,
    tags=['identity_document_handling'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def govid(body: GovidCertificatePostRequest = None):
    """
    ID Card
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/phcer/certificate',
    description=""" API to verify Pharmacist Registration Certificate. """,
    tags=['professional_registration_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def phcer(body: PhcerCertificatePostRequest = None):
    """
    Pharmacist Registration Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
